db:
  image: postgres
web:
  dockerfile: Dockerfile
  build: .
  links:
    - db
  environment:
    - PORT=9000
    - NODE_ENV=development
    - DB_HOST=db
    - DB_USER=postgres
    - DB_PASSWORD=postgres
    - DB_DATABASE=guidedSelling
  volumes:
    - .:/home/app/project
    - /home/app/project/node_modules
    - /home/app/project/client/bower_components
  ports:
    - '9000:9000'
    - '35729:35729'
