FROM ubuntu:14.04

MAINTAINER Ivan Turkovic <ivan.turkovic@gmail.com>

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get -qq update
RUN apt-get install \
    openssh-client \
    wget \
    nginx \
    supervisor \
    curl \
    bc \
    gcc \
    python \
    python-dev \
    python-setuptools \
    libffi-dev \
    ca-certificates \
    dialog \
    make \
    g++ \
    git && \
    mkdir -p /etc/nginx && \
    mkdir -p /home/app/project/app && \
    mkdir -p /run/nginx && \
    mkdir -p /var/log/supervisor

RUN apt-get install -y nodejs npm
# TODO could uninstall some build dependencies

# debian installs `node` as `nodejs`
RUN update-alternatives --install /usr/bin/node node /usr/bin/nodejs 10

RUN rm -rf /var/cache/apt/archives

RUN pip install -U letsencrypt && \
    mkdir -p /etc/letsencrypt/webrootauth

ADD conf/build.sh /usr/bin/
RUN build.sh

#RUN git clone https://github.com/letsencrypt/letsencrypt /opt/letsencrypt

WORKDIR /home/app/project
RUN npm install -g bower gulp

ADD conf/supervisord.conf /etc/supervisord.conf

# Copy our nginx config
RUN rm -Rf /etc/nginx/nginx.conf
ADD conf/nginx.conf /etc/nginx/nginx.conf

# nginx site conf
RUN mkdir -p /etc/nginx/sites-available/ && \
mkdir -p /etc/nginx/sites-enabled/ && \
mkdir -p /etc/nginx/ssl/ && \
rm -Rf /home/app/project/* && \
mkdir -p /home/app/project/
mkdir -p /home/app/project/node_modules/
ADD conf/nginx-site.conf /etc/nginx/sites-available/default.conf
ADD conf/nginx-site-ssl.conf /etc/nginx/sites-available/default-ssl.conf
RUN ln -s /etc/nginx/sites-available/default.conf /etc/nginx/sites-enabled/default.conf

# Add Scripts
ADD scripts/start.sh /start.sh
ADD scripts/pull /usr/bin/pull
ADD scripts/push /usr/bin/push
ADD scripts/letsencrypt-setup /usr/bin/letsencrypt-setup
ADD scripts/letsencrypt-renew /usr/bin/letsencrypt-renew
RUN chmod 755 /usr/bin/pull && chmod 755 /usr/bin/push && chmod 755 /usr/bin/letsencrypt-renew && chmod 755 /usr/bin/letsencrypt-setup && chmod 755 /start.sh

# copy in code
# ADD src/ /home/app/project/
RUN mkdir -p /var/log/node/


EXPOSE 443 80

#CMD ["/usr/bin/supervisord", "-n", "-c",  "/etc/supervisord.conf"]
CMD ["/start.sh"]
